cliDefaults:
  run:
    plan: false
    sequential: true
includes: []
imports:
  stan-core: 
    - '../stan-core/.stan/system/stan.requirements.md'
    - '../stan-core/.stan/system/stan.todo.md'
    - '../stan-core/dist/types/index.d.ts'
    - '../stan-core/.stan/interop/stan-cli/**'
excludes:
  - "*.local"
  - assets
  - CHANGELOG.md
  - docs
  - docs-src/**
  - diagrams/**
  - package-lock.json
scripts:
  typecheck: npm run typecheck
  lint: npm run lint:fix
  test: npm run test -- --no-color
  build: npm run build
  docs: npm run docs -- --emit none
  knip: npm run knip
patchOpenCommand: code -g {file}
stanPath: .stan
